config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'hosts#index'
  resources :users, only: [:show, :edit, :update] do
    member do
      post :edit_varification
    end
  end
  resources :hosts do
    collection do
      get 'search'
      get 'rooms'
      post 'bedrooms'
      post 'bathrooms'
      post 'location'
      post 'amenities'
    end
    member do
    # ステップ１
      get 'rooms'
      post 'bedrooms'
      post 'bathrooms'
      post 'location'
      post 'amenities'
    # ステップ２
      get 'photos'
      patch 'description'
      patch 'title'
    # ステップ３
      get 'guest-requirements'
      get 'house-rules'
      get 'review-guest-requirements'
      get 'review-how-guests-book'
      get 'keep-calendar-up-to-date'
      get 'availability-questions'
      post 'availability-questions'
      patch 'price'
      post 'booking-scenarios'
      get 'additional-pricing'
      get 'local-law'
      # patch 'house-rules'
      # patch 'review-guest-requirements'
      # get 'review-how-guests-book'
      # get 'keep-calendar-up-to-date'
      # patch 'availability-questions'
      # patch 'calendar'
      # patch 'price'
      # patch 'additional-pricing'
    end
  end
  resources :categories, only: [] do
    resources :house_types, only: [:index, :show] do
    end
  end
end

app/models/host.rb
class Host < ApplicationRecord
  has_many :categories
  belongs_to :user
  has_many :amenities, through: :host_amenities
  has_many :safety_amenities, through: :host_safety_amenities

  enum size_of_building: [ :size_of_building_2_5, :size_of_building_6_10, :size_of_building_11_20, :size_of_building_21_30, :size_of_building_31_40, :size_of_building_41_50, :size_of_building_50_puls ]
  enum room_type: [ :entire_house, :private_room, :share_room ]
  enum is_this_room_using_guest_only: [ :bedroom_count_1, :bedroom_count_2, :bedroom_count_3, :bedroom_count_4, :bedroom_count_5, :bedroom_count_6, :bedroom_count_7, :bedroom_count_8, :bedroom_count_9, :bedroom_count_10, ]
  enum have_you_experienced_lending_a_room: [ :beginner, :experienced ]
  enum how_often_do_you_want_to_stay: [ :still_dont_know, :part_time, :frequently ]
  enum currency: [ :usd, :aud, :cad, :gbp, :cny, :eur, :rub, :vnd, :inr, :myr, :thb, :krw, :jpy, :sek, :dkk]
end

app/controllers/hosts_controller.rb
class HostsController < ApplicationController
  before_action :set_host, only: [:rooms, :bedrooms, :bathrooms, :location, :amenities]
  before_action :set_user
  before_action :set_host_id, only: [ \
    :show, \
    :photos, \
    :description, \
    :title, \
    :guest_requirements, \
    :house_rules, \
    :review_guest_requirements, \
    :review_how_guests_book, \
    :keep_calendar_up_to_date, \
    :availability_questions, \
    :calendar, \
    :price, \
    :additional_pricing, \
    :local_law, \
    :update \
    ]

  def index
  end

  def rooms
  end

  def bedrooms
    session[:user_category] = host_params[:category]
    session[:user_house_type] = host_params[:house_type]
    session[:user_room_type] = host_params[:room_type]
    set_sessions
  end

  def bathrooms
    session[:user_capacity] = host_params[:capacity]
    session[:user_num_bedroom] = host_params[:num_bedroom]
    set_sessions
  end

  def location
    session[:user_num_of_bath] = host_params[:num_of_bath]
    set_sessions
  end

  def amenities
    session[:user_country] = host_params[:country]
    session[:user_postal_code] = host_params[:postal_code]
    session[:user_state] = host_params[:state]
    session[:user_city] = host_params[:city]
    session[:user_address_line_1] = host_params[:address_line_1]
    session[:user_address_line_2] = host_params[:address_line_2]
    set_sessions
    @amenity = Amenity.new
    @safety_amenity = SafetyAmenity.new
  end

  def create
    set_sessions
    @host = Host.new( \
      user_id: @user.id,\
      category: @user_category, \
      house_type: @user_house_type, \
      room_type: @user_room_type, \
      capacity: @user_capacity, \
      num_bedroom: @user_num_bedroom, \
      num_of_bath: @user_num_of_bath, \
      country: @user_country, \
      postal_code: @user_postal_code, \
      state: @user_state, \
      city: @user_city, \
      address_line_1: @user_address_line_1, \
      address_line_2: @user_address_line_2 \
      )
    @host.save
    @amenity = Amenity.new(amenity_params)
    @amenity.save
    @safety_amenity = SafetyAmenity.new(safety_amenity_params)
    @safety_amenity.save
    if @host.save && @amenity.save && @safety_amenity.save
      redirect_to host_path(id: @host.id)
    else
      render :amenities
    end
  end

  def show
  end

  def photos
  end

  def description
  end

  def title
    session[:house_description] = host_params[:house_description]
  end

  def guest_requirements
    @host = Host.new
  end

  def house_rules
    @host = Host.new
  end

  def review_guest_requirements
    @host = Host.new
  end

  def review_how_guests_book
    @host = Host.new
  end

  def keep_calendar_up_to_date
    @host = Host.new
  end

  def availability_questions
  end

  def calendar
  end

  def price
  end

  def booking_scenarios
  end

  def additional_pricing
  end

  def local_law
  end

  def update
    session[:user_basic_charge] = host_params[:basic_charge]
    session[:house_name] = host_params[:house_name]
    set_sessions
    @host = Host.find(params[:id])
    if @host.user_id == current_user.id
      @host.update( \
        user_id: @user.id,\
        category: @user_category, \
        house_type: @user_house_type, \
        room_type: @user_room_type, \
        capacity: @user_capacity, \
        num_bedroom: @user_num_bedroom, \
        num_of_bath: @user_num_of_bath, \
        country: @user_country, \
        postal_code: @user_postal_code, \
        state: @user_state, \
        city: @user_city, \
        address_line_1: @user_address_line_1, \
        address_line_2: @user_address_line_2, \
        house_description: @house_description, \
        house_name: @house_name, \
        basic_charge: @basic_charge \
        )
      redirect_to host_path(id: @host.id)
    end
  end

  private
  def set_sessions
    @user_category = session[:user_category]
    @user_house_type = session[:user_house_type]
    @user_room_type = session[:user_room_type]
    @user_capacity = session[:user_capacity]
    @user_num_bedroom = session[:user_num_bedroom]
    @user_num_of_bath = session[:user_num_of_bath]
    @user_country = session[:user_country]
    @user_postal_code = session[:user_postal_code]
    @user_state = session[:user_state]
    @user_city = session[:user_city]
    @user_address_line_1 = session[:user_address_line_1]
    @user_address_line_2 = session[:user_address_line_2]
    @house_description = session[:house_description]
    @house_name = session[:house_name]
    @basic_charge = session[:user_basic_charge]
  end

  def host_params
    params.require(:host).permit( \
      :category, \
      :house_type, \
      :size_of_building, \
      :room_type, :capacity, \
      :num_bedroom, \
      :num_of_bath, \
      :country, \
      :postal_code, \
      :state, \
      :city, \
      :address_line_1, \
      :address_line_2, \
      :house_description, \
      :house_name, \
      :basic_charge \
    )
  end

  def amenity_params
    params.require(:amenity).permit(:necessity, :wifi, :shampoo, :closet, :tv, :air_con, :breakfast, :desk, :heater, :steam_iron, :hair_dryer, :pet, :entrance)
  end

  def safety_amenity_params
    params.require(:safety_amenity).permit(:smoke_sensor, :hochiki, :first_aid_kit, :emergency_info, :fire_extinguisher, :private_room)
  end

  def set_user
    @user = current_user
  end

  def set_host
    @host = Host.new
  end

  def set_host_id
    @host = Host.find(params[:id])
  end
end

app/views/hosts/_house.html.haml
.introduction_house
  = link_to '' do
    = image_tag 'house_sample.png', widh: '273px', height: '182px',alt: 'user_photo'
  .tags ログハウス貸切 · マカワオ
  .name Adorable Garden Gingerbread House
  .charge 18,741
  .rate ここに評価が表示されます

app/views/hosts/amenities.haml
.contents
  .left_content
    %h2 掲載するのはどんなお部屋ですか?
    .form_box
      = form_for @host do |f|
        .location
          = f.hidden_field :category
          = f.hidden_field :house_type
          = f.hidden_field :room_type
          = f.hidden_field :capacity
          = f.hidden_field :num_bedroom
          = f.hidden_field :num_of_bath
          = f.hidden_field :country
          = f.hidden_field :postal_code
          = f.hidden_field :state
          = f.hidden_field :city
          = f.hidden_field :address_line_1
          = f.hidden_field :address_line_2
          %p
            = f.label :address_line_2, "次に建物タイプを選んでください"
          %p
            = f.text_field :address_line_2, placeholder: "例）１０１号室"
          .continue-btn
            = link_to "次へ", host_path
  .right_content

app/views/hosts/amenities.html.haml
.contents
  .left_content.col-lg-7.col-md-5
    %h2 ご用意するアメニティ・設備は?
    .form_box

      = form_for @host, url: {controller: "hosts", action: "create"} do |f|
        = f.hidden_field :category
        = fields_for @amenity, url: {controller: "hosts", action: "create"} do |a|
          %p
            = a.label :necessity, "必需品 タオル、シーツ、石鹸、トイレットペーパー、枕"
          %p
            = a.check_box :necessity
          %p
            = a.label :wifi, "Wi-Fi"
          %p
            = a.check_box :wifi
          %p
            = a.label :shampoo, "シャンプー"
          %p
            = a.check_box :shampoo
          %p
            = a.label :closet, "クローゼット/タンス"
          %p
            = a.check_box :closet
          %p
            = a.label :tv, "テレビ"
          %p
            = a.check_box :tv
          %p
            = a.label :air_con, "エアコン"
          %p
            = a.check_box :air_con
          %p
            = a.label :breakfast, "朝食、コーヒー、お茶"
          %p
            = a.check_box :breakfast
          %p
            = a.label :desk, "机・ワークスペース"
          %p
            = a.check_box :desk
          %p
            = a.label :heater, "暖炉・薪ストーブ・囲炉裏"
          %p
            = a.check_box :heater
          %p
            = a.label :steam_iron, "アイロン"
          %p
            = a.check_box :steam_iron
          %p
            = a.label :hair_dryer, "ヘアドライヤー"
          %p
            = a.check_box :hair_dryer
          %p
            = a.label :pet, "ペットOK"
          %p
            = a.check_box :pet
          %p
            = a.label :entrance, "専用の玄関"
          %p
            = a.check_box :entrance

        %span 安全対策のアメニティ
        = fields_for @safety_amenity, url: {controller: "hosts", action: "create"} do |s|
          %p
            = s.label :smoke_sensor, "煙感知器 地域の法令をお確かめください。各部屋に煙検知器設置を義務づけている地域もあります。"
          %p
            = s.check_box :smoke_sensor
          %p
            = s.label :hochiki, "一酸化炭素検知器 地域の法令をお確かめください。各部屋に一酸化炭素検知器設置を義務づけている地域もあります。"
          %p
            = s.check_box :hochiki
          %p
            = s.label :first_aid_kit, "応急手当セット"
          %p
            = s.check_box :first_aid_kit
          %p
            = s.label :emergency_info, "防災カード 緊急連絡先と避難情報は掲示しておきましょう。"
          %p
            = s.check_box :emergency_info
          %p
            = s.label :fire_extinguisher, "消火器"
          %p
            = s.check_box :fire_extinguisher
          %p
            = s.label :private_room, "寝室は鍵付きドア 安全性とプライバシーが保たれる鍵付きの個室のことです。"
          %p
            = s.check_box :private_room

        .btn.btn-success.btn-sm
          = f.submit "完了"

  .right_content.col-lg-7.col-md-5
    .right_content__advice
      生活必需品を揃えておくと、ゲストも自分の家のようにくつろげます。
      %br
      %br
      朝食を用意する方もいれば、コーヒーやお茶だけにする方も。どれも義
      務というわけではないけれど、あると温かいおもてなしの気持ちが伝わ
      るアイテムです。

app/views/hosts/availability_questions.html.haml
.contents
  .left_content
    %h2 質問に答えて予約の設定を進めましょう
    .form_box
      = form_for @host, url: price_host_path(@host.id) do |f|
        .availability_questions
          .experience-question
            %p
              = f.label :have_you_experienced_lending_a_room, "今までお部屋を貸したことはありますか？"
            %p
              = f.select :have_you_experienced_lending_a_room, Host.have_you_experienced_lending_a_rooms_i18n.invert
          .occupancy-question
            %p
              = f.label :how_often_do_you_want_to_stay, "泊めたい頻度は？"
            %p
              = f.select :how_often_do_you_want_to_stay, Host.how_often_do_you_want_to_stays_i18n.invert
        .btn.btn-success.btn-sm{style: "margin-top: 30px;"}
          = f.submit "次へ", class: "next"
  .right_content

app/views/hosts/bathrooms.html.haml
.contents
  .left_content
    %h2 掲載するのはどんなお部屋ですか?
    .form_box
      = form_for @host, url: {action: 'location'} do |f|
        %p
          = f.label :num_of_bath, "バスルーム数は？"
        %p
          = f.text_field :num_of_bath, class: "bathroom_count", value: "1"
        .btn.btn-success.btn-sm
          = f.submit "次へ", class: "next"
  .right_content

app/views/hosts/description.html.haml
.contents
  .left_content
    %h2 説明文を編集する
    .form_box
      = form_for @host, url:  title_host_path(@host.id) do |f|
        .description
          %p
            = f.label :house_description, "概要"
          %p
            = f.text_area :house_description, class: "house_description", placeholder: "インテリア、照明、近くにあるものなどを説明してください。"
          %p
            = f.label :house_description, "こんな旅にぴったりの宿です"
          %p
            = f.check_box :house_description, {multiple: true}, '子ども連れファミリー', nil
          %p
            = f.label :house_description, '子ども連れファミリー'
          %p
            = f.check_box :house_description, {multiple: true}, '団体', nil
          %p
            = f.label :house_description, '団体'
          %p
            = f.check_box :house_description, {multiple: true}, 'ペット同伴', nil
          %p
            = f.label :house_description, 'ペット同伴'
          %p
            = f.label :house_description, "さらに追加 (任意)"
            %h5 入力率わずか30%。意外と盲点です

          .btn.btn-success.btn-sm
            = f.submit "次へ", class: "next"
  .right_content

app/views/hosts/guest_requirements.html.haml
.col-md-7
  .left-col-content
    %h2 Airbnbが求めるゲスト要件をチェック
    .all_guest_requirement
      %h4 　Airbnbが全ゲストに確認を求めるもの:
      %h5 ✅　メールアドレス
      %h5 ✅　認証済みの電話番号
      %h5{style: "padding-bottom: 20px;"} ✅　支払い情報
    .before_all_guest_requirement
      %h4 あなたが全ゲストに予約前に確認を求めるもの:
      %h5 ✅　あなたのハウスルールに同意すること
      %h5 ✅　ホストに旅行内容をメッセージで伝える
      %h5 ✅　宿泊人数をホストに伝える
      %h5 ✅　チェックイン時刻の申告 (到着まで2日未満の予約の場合)
      -# 仮置きボタン
    .continue-btn
      = link_to "戻る", host_path
      = link_to "次へ", house_rules_host_path
    .col-md-5.hidden-xs
      .right-col-content

app/views/hosts/house_rules.html.haml
.col-md-7
  .left-col-content
    .title
      %h2 滞在中のハウスルールを設定しましょう
      -# スイッチボタン部分のハウスルール
      .main_house_rules
        .main_house_rules__box
          .form-groyp.row
            .main_house_rules__text__child
              %label{class: 'form_label', name: 'child'} 子ども(2-12歳)OK
            .btn-group{"data-toggle": "buttons"}
              %label.btn.btn-outline-secondary{style: "width:40%"}
                %input{type: 'radio', name: 'sex', value: 0} いいえ
              %label.btn.btn-outline-secondary{style: "width:40%"}
                %input{type: 'radio', name: 'sex', value: 1}　はい
        .main_house_rules__box
          .form-groyp.row
            .main_house_rules__text__baby
              %label{class: 'form_label', name: 'baby'} 乳幼児(2歳未満)OK
            .btn-group{"data-toggle": "buttons"}
              %label.btn.btn-outline-secondary{style: "width:40%"}
                %input{type: 'radio', name: 'baby', value: 0} いいえ
              %label.btn.btn-outline-secondary{style: "width:40%"}
                %input{type: 'radio', name: 'baby', value: 1}　はい
        .main_house_rules__box
          .form-groyp.row
            .main_house_rules__text__pet
              %label{class: 'form_label', name: 'pet'} ペットOK
            .btn-group{"data-toggle": "buttons"}
              %label.btn.btn-outline-secondary{style: "width:40%"}
                %input{type: 'radio', name: 'pet', value: 0} いいえ
              %label.btn.btn-outline-secondary{style: "width:40%"}
                %input{type: 'radio', name: 'pet', value: 1}　はい
        .main_house_rules__box
          .form-groyp.row
            .main_house_rules__text__smoking
              %label{class: 'form_label', name: 'smoking'} 喫煙OK
            .btn-group{"data-toggle": "buttons"}
              %label.btn.btn-outline-secondary{style: "width:40%"}
                %input{type: 'radio', name: 'smoking', value: 0} いいえ
              %label.btn.btn-outline-secondary{style: "width:40%"}
                %input{type: 'radio', name: 'smoking', value: 1}　はい
        .main_house_rules__box
          .form-groyp.row
            .main_house_rules__text__event
              %label{class: 'form_label', name: 'event'} イベント&パーティOK
            .btn-group{"data-toggle": "buttons"}
              %label.btn.btn-outline-secondary{style: "width:40%"}
                %input{type: 'radio', name: 'event', value: 0} いいえ
              %label.btn.btn-outline-secondary{style: "width:40%"}
                %input{type: 'radio', name: 'event', value: 1}　はい
      -# 追加ハウスルール部分(フェイク)
      .add_house_rules
        .add_house_rules__text{style: "margin-top: 50px;"}
          %h4 追加ルール
        .add_house_rules__text_filed
          %input{type: 'text_filed', placeholder: '騒音禁止の時間帯、土足厳禁など', style: 'height: 50px;' 'width: 300px;'}
          %input{type: 'submit', value: "追加", style: 'height: 50px;' 'width: 100px;'}
      -# お家についてゲストが事前に知っておくべきこと部分はつくらない
      .continue-btn
        = link_to "戻る", guest_requirements_host_path
        = link_to "次へ", review_guest_requirements_host_path
.col-md-5.hidden-xs
  .right-col-content
    = image_tag "host/show_migi.png", height: "700px"

app/views/hosts/index.html.haml
%h3 世界のお家
= render partial: 'house'
= render partial: 'house'
= render partial: 'house'
= render partial: 'house'
= render partial: 'house'
= render partial: 'house'
= render partial: 'house'
= render partial: 'house'
= render partial: 'house'

app/views/hosts/location.html.haml
.contents
  .left_content
    %h2 掲載するのはどんなお部屋ですか?
    .form_box
      = form_for @host, url: amenities_hosts_path do |f|
        %p
          = f.label :country, "国"
        %p
          = f.text_field :country, placeholder: "例) 日本", class: "form-large"
        %p
          = f.label :postal_code, "郵便番号"
        %p
          = f.number_field :postal_code, placeholder: "例）123-4567", class: "form-large"
        %p
          = f.label :state, "都道府県(例: Tokyo)"
        %p
          = f.text_field :state, placeholder: "例）東京都", class: "form-large"
        %p
          = f.label :city, "市区町村(例: Minato-ku)"
        %p
          = f.text_field :city, placeholder: "例）中央区", class: "form-large"
        %p
          = f.label :address_line_1, "所番地(例: 1-1-1 Roppongi)※数字は半角"
        %p
          = f.text_field :address_line_1, placeholder: "例）銀座一丁目１−１", class: "form-large"
        %p
          = f.label :address_line_2, "アパート名、部屋番号(任意)"
        %p
          = f.text_field :address_line_2, placeholder: "例）１０１号室", class: "form-large"
        .btn.btn-success.btn-sm
          = f.submit "次へ", class: "next"
  .right_content

app/views/hosts/photos.html.haml
-# （仮）
-# 全文消してください
.contents
  .left_content
    %h2 最大何人まで宿泊可能ですか?
    .form_box
      = form_for @host, url: description_host_path(@host.id) do |f|
        .bedroom

          .btn.btn-success.btn-sm
            = f.submit "次へ", class: "next"
  .right_content

app/views/hosts/review_guest_requirements.html.haml
.col-md-7
  .left-col-content
    %h2 予約の要件を確認しよう
    .all_guest_requirement
      %h4 　Airbnbが求めるゲスト要件
      %h5 ✅　メールアドレス
      %h5 ✅　認証済みの電話番号
      %h5 ✅　支払い情報
      %h5 ✅　旅行に関するメッセージ
      %h5 ✅　チェックイン時刻の申告(直前予約の場合)
    .add_all_guest_requirement{style: "padding: 20px 0 20px;"}
      %h4 追加の要件
      %h5 追加の要件はありません
    .before_all_guest_requirement
      %h4 ハウスルール
      %h5 ✅　乳幼児(2歳未満)OK
      %h5 ✅　子供に安全とは言えない/不向き (2-12歳)
      %h5 ✅　チェックインは15:00から
      -# 仮置きボタン
    .continue-btn{style: "padding-top: 40px;"}
      = link_to "戻る", house_rules_host_path
      = link_to "次へ", review_how_guests_book_host_path
    .col-md-5.hidden-xs
      .right-col-content

app/views/hosts/rooms.html.haml
.contents
  .left_content
    %h2 掲載するのはどんなお部屋ですか?
    .form_box
      = form_for @host, url: bedrooms_hosts_path do |f|
        .category
          %p
            = f.label :category, "まずカテゴリを絞りましょう"
          %p
            - category_options = Category.order(:id).map { |c| [c.name, c.name, data: { house_type_path: category_house_types_path(c) }] }
            = f.select :category, category_options, { include_blank: "1つ選択してください" } , class: 'select-category', selected: @user_category
          %p
            = f.label :house_type, "次に建物タイプを選んでください"
          %p
            = f.select :house_type, [],  { include_blank: "建物タイプを選択" } , class: 'select-house-type'
          %p.house-discription
        .room
          / %p
          /   = f.label :num_room, "物件の総部屋数は？"
          / %p
          /   = f.select :num_room, Host.size_of_buildings_i18n.invert
          %p
            = f.label :room_type, "部屋タイプは？"
          %p
            = f.select :room_type, Host.room_types_i18n.invert
          .btn.btn-success.btn-sm
            = f.submit "送信", class: "next"
  .right_content

app/views/hosts/title.html.haml
.contents
  .left_content
    %h2 物件に名前をつける
    .form_box
      = form_for @host do |f|
        .title
          %p
            = f.text_field :house_name, class: "house_name", placeholder: "リスティングのタイトル"

          .btn.btn-success.btn-sm
            = f.submit "次へ", class: "next"
  .right_content