config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'hosts#index'
  resources :users, only: [:show, :edit, :update] do
    member do
      post :edit_varification
    end
  end
  resources :hosts do
    collection do
      get 'search'
      get 'rooms'
      post 'bedrooms'
      post 'bathrooms'
      post 'location'
      post 'amenities'
    end
    member do
    # ステップ１
      get 'rooms'
      post 'bedrooms'
      post 'bathrooms'
      post 'location'
      post 'amenities'
    # ステップ２
      get 'photos'
      patch 'description'
      patch 'title'
    # ステップ３
      get 'guest-requirements'
      get 'house-rules'
      get 'review-guest-requirements'
      get 'review-how-guests-book'
      get 'keep-calendar-up-to-date'
      get 'availability-questions'
      post 'availability-questions'
      patch 'price'
      post 'booking-scenarios'
      get 'additional-pricing'
      get 'local-law'
      # patch 'house-rules'
      # patch 'review-guest-requirements'
      # get 'review-how-guests-book'
      # get 'keep-calendar-up-to-date'
      # patch 'availability-questions'
      # patch 'calendar'
      # patch 'price'
      # patch 'additional-pricing'
    end
  end
  resources :categories, only: [] do
    resources :house_types, only: [:index, :show] do
    end
  end
end

app/views/layouts/_notification.html.haml
.notification
	- flash.each do |key, value|
		= content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %header
    .container
      %meta{content: "text/html; charset=UTF-8", 'http-equiv': "Content-Type"}/
      %title AirbnbClone
      = csrf_meta_tags
      = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
      = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %header
      .head_inner.clearfix
        .col-md-5.col-sm-12
          .head_icon
            = link_to hosts_path do
              = image_tag "layout/logo.png", width: "45px", height: "45px", alt: "logo"
          .head_search
            %form{action: search_hosts_path, method: :get}
              %input{name: 'area', class: 'head_search__search_box', placeholder: '「トロント」などエリアを入力'}
        .col-md-7.hidden-sm.hidden-xs
          %ul
            - if user_signed_in?
              %li
                = link_to "部屋を掲載"
              %li
                = link_to "ホスト", rooms_hosts_path
              %li
                = link_to "お気に入り"
              %li
                = link_to "旅行"
              %li
                = link_to "メッセージ"
              %li
                = link_to "クーポン"
              %li
                = link_to "ヘルプ"
              .btn-group.drop-left.btn-sm
                %button.btn.btn-default.btn-sm.dropdown-toggle{"aria-expanded" => "false", "data-toggle" => "dropdown", type: "button"}
                  = "#{@user.first_name}さん"
                %span.caret1
                %ul.dropdown-menu.dropdown-menu-right{role: "menu"}
                  %li.info{role: "presentation"}
                    = link_to "プロフィール編集", "/users/#{@user.id}/edit", method: :get, role: "menuitem",tabindex: "-1"
                  %li.info{role: "presentation"}
                    = link_to "友達を編集する", role: "menuitem", tabindex: "-1"
                  %li.info{role: "presentation"}
                    = link_to "アカウントを設定する", role: "menuitem", tabindex: "-1"
                  %li.info{role: "presentation"}
                    = link_to "ガイドブック", role: "menuitem", tabindex: "-1"
                  %li.info{role: "presentation"}
                    = link_to "Airbnb法人プログラム", "menuitem", tabindex: "-1"
                  %li.info{role: "presentation"}
                    = link_to "ログアウト", destroy_user_session_path, method: :delete, role: "menuite", tabindex: "-1"
            - else
              %li
                = link_to "ホストをはじめる"
              %li
                = link_to "ヘルプ"
              %li
                = link_to "アカウント作成", new_user_registration_path
              %li
                = link_to "ログイン", new_user_session_path, method: :post
    %article.clearfix
      = yield

    %footer
      .container.hidden-xs
        .col-xs-3
          %h4 Airbnb
          %ul
            %li
              = link_to "採用情報"
            %li
              = link_to "プレス"
            %li
              = link_to "ポリシー"
            %li
              = link_to "ヘルプ"
            %li
              = link_to "ダイバーシティ&"
            %li
              = link_to "ビロンギング"
        .col-xs-3
          %h4 スタッフのおすすめ
          %ul
            %li
              = link_to "信頼&安全"
            %li
              = link_to "友達を招待する"
            %li
              = link_to "Airbnb Citizen"
            %li
              = link_to "出張"
            %li
              = link_to "ガイドブック"
            %li
              = link_to "Airbnbmag"
        .col-xs-3
          %h4 ホスティング
          %ul
            %li
              = link_to "ホストになる理由"
            %li
              = link_to "おもてなしの心"
            %li
              = link_to "ホストの責任"
            %li
              = link_to "コミュニティセンター"
        .col-xs-3
          %h4 sns
          %ul
            %li
              = link_to "利用規約"
            %li
              = link_to "プライバシー"
            %li
              = link_to "サイトマップ"
      .container
        .foot2.col-xs-12
          .foot2__left
            %p
              = image_tag "layout/logo.png",  width: "24px", height: "24px", alt: "logo"
            %p
              ©Airbnb, Ink
          .foot2__right
            .language_btn 言語設定ボタン
            .currency_btn 通貨設定ボタン